environment_params:
  env_name: 'pong'
  grid_size: [84, 84]
  delta_preprocessing: True
  last_n: 1

rl_params:
  memory_structure: 'asynchronous_methods'
  memory_structure_params: {'actor_critic_method': False}
  gamma: 0.99
  max_steps: 30000
  n_steps_ahead: 5

model_params:
  class: 'vw_python'
  loss_function: 'squared'
  l2: 0.0000001
  l: 0.15
  b: 27
  lrq: 'sd100'
  resume: False

bandit_params:
  start_epsilon: 0.99
  anneal_epsilon_timesteps: 2000

training_params:
  epochs: 2700
  use_processes: False
  number_of_threads: 8

testing_params:
  test_games: 2
  display_games: 0